# Generated by Django 5.2.6 on 2025-09-23 13:20

import applications.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[applications.users.models.validate_dob]),
        ),
    ]
